### ISSUE TITLE
notifyPort not populated if CommandPort and NotifyPort are same

### ISSUE THREAD

**Issue by yocha** [xlab/at#19]
https://github.com/xlab/at/blob/7884b63edf8326b47be93c99e3e56192a98fd984/at.go#L372

This logic  result in notifyPort = nil if CommandPort equals NotifyPort or NotifyPort not provided. As a result sanity check fails.

**Comment by xlab** [comment]
Hm, this is very strange to have both on the same serial port.
I don't think it would work. But the sanityCheck might be adjusted to skip notification port for example, if it's nil.

**Comment by yocha** [comment]
ya... maybe I'm not understanding use cases for command and notify ports.  I'm try to make this library work with Raspberry Pi 3B+ with SIM7100A GSM development board.

**Comment by xlab** [comment]
@yocha my Huawei dongle creates 2-3 serial ports, and `notify` acts like a message queue for events, and `command` port acts like an API server. That's the difference. I'm not sure how it works on a non-customer board. But you may find a work around and contribute it ;)

**Comment by yocha** [comment]
will try...
