### ISSUE TITLE
Support of TP-UDHI

### ISSUE THREAD

**Issue by azman0101** [xlab/at#2]
Hi,

Do you plan to support TP-UDHI flag and then multiple part SMS ?

Thxs

**Comment by xlab** [comment]
TP-UDHI: https://github.com/xlab/at/blob/master/sms/sms.go#L465-L467

```
	if s.UserDataHeaderIndicator {
		header |= 0x01 << 5 // 5 bit
	}
```

So it's there, but not used actually. Multipart messages are hard to implement properly, https://en.wikipedia.org/wiki/GSM_03.40 (see Message Content). You can implement and sell a pull request.

**Comment by azman0101** [comment]
Hello, Thanks for your response.
I have just started to learn Go :)

For those how need a fully implemented lib : http://smspdu.benjaminerhart.com
