### ISSUE TITLE
What is NotifyPort

### ISSUE THREAD

**Issue by ssadok** [xlab/at#3]
Hi please i didn't understand what is the NotifyPortPath

**Comment by xlab** [comment]
Hi! 

There are two ports: for giving commands and for listening notifications 
<img width="450" alt="screen shot 2017-08-02 at 13 28 33" src="https://user-images.githubusercontent.com/477998/28869861-d83db7be-7786-11e7-93f1-627b895ad899.png">

AT starts watching on the notification port, so it could react on various event about incoming SMS, etc
https://github.com/xlab/at/blob/master/at.go#L223

**Comment by ssadok** [comment]
and if i m in windows
i put CommandPortPath COM1 and NotifyPortPath COM1 ?

**Comment by xlab** [comment]
@ssadok I'm not sure about that, sorry. I'll check when i get windows

**Comment by ssadok** [comment]
https://github.com/xlab/at/blob/master/at.go#L374
i think that port if is the same it will be busy.

**Comment by xlab** [comment]
@ssadok it cannot be the same, there is no multiplexing. Usually Huawei modems create 3-5 serial devices in the system.

**Comment by ssadok** [comment]
i use this 
http://www.ebay.com/itm/GSM-GPRS-Modem-Pool-16-ports-for-Wavecom-Q2406-Module-USB-AT-Commands-Dual-Band-/231693083428

**Comment by ssadok** [comment]
thank you i will test it and get back to you shortly
