### ISSUE TITLE
Encoding with 0x01 value

### ISSUE THREAD

**Issue by scr34m** [xlab/at#34]
I've received a message which one uses 0x01 as encoding, so i extended then encoding list with a new GSM7 type and looks good to me. Already forked and can i send a PR to merge or You need more information?

The raw message is this: 099143060780218245F0040B911477392946F900014270925120818005379C8D5603

**Comment by xlab** [comment]
Hello, it's ok to send a PR

**Comment by scr34m** [comment]
Okay PR is sent, closing this.
