### ISSUE TITLE
sms.go error

### ISSUE THREAD

**Issue by jloup** [xlab/at#6]
go version: `go version go1.10.2 linux/amd64`

`go get github.com/xlab/at`

outputs:
```
# github.com/xlab/at/sms
../../go/src/github.com/xlab/at/sms/sms.go:386:5: id declared and not used
../../go/src/github.com/xlab/at/sms/sms.go:387:5: total declared and not used
../../go/src/github.com/xlab/at/sms/sms.go:388:5: num declared and not used
```

**Comment by googolgl** [comment]
I confirm
go version go1.10 linux/amd64

**Comment by lsdev75** [comment]
Same issue with go version 1.9.2  linux/amd64

No news?

**Comment by xlab** [comment]
I reverted #5 please re-clone the repo and check. Thanks.
