### ISSUE TITLE
Incorrect Gsm7Bit content length in Deliver message type

### ISSUE THREAD

**Issue by LeeVidor** [xlab/at#8]
Line 272 of sms.go needs removing. It adds incorrect content length for Gsm7Bit encoding type when encoding deliver message type. 

_sms.UserDataLength = byte(len(userData))_

**Comment by xlab** [comment]
@LeeVidor hi, would like to create a PR?
Also, is this only one place with that mistake?

**Comment by LeeVidor** [comment]
Yes, this is the only one found. For example the code is correct for submit message type/
Created PR https://github.com/xlab/at/pull/10
